#include<stdio.h>
int main()
{
    int a[13],b[13],z,j,i,bar_variable,R1,R2,S1,S2,D1,D2;              // a[13]->White,b[13]->Black
    int R1_moved=0;
    int R2_moved=0;
    char c1,c2,d1,d2;
    printf("Fill White's Home:\n");
    for(i=1;i<=12;i++)
        scanf("%d",&a[i]);
    printf("Fill Black's Home:\n");
    for(i=1;i<=12;i++)
        scanf("%d",&b[i]);
    printf("Value of dice\n");
    scanf("%d%d",&R1,&R2);
    printf("Value of bar_variable\n");
    scanf("%d",&bar_variable);
    while(bar_variable>0)
    {
        if(a[13-R1]>=0&&bar_variable>0)
        {
            bar_variable--;
            a[13-R1]++;
            c1='Z';
            d1='A';
            S1=0;
            D1=13-R1;
            R1_moved=1;
        }
        if(a[13-R2]>=0&&bar_variable>0)
        {
            bar_variable--;
            a[13-R2]++;
            c2='Z';
            d2='A';
            S2=0;
            D2=13-R2;
            R2_moved=1;
        }
        if(a[13-R1-R2]>=0&&bar_variable>0)
        {
            bar_variable--;
            a[13-R1-R2]++;
            printf("Z->A%d\n",13-R1-R2);
            printf("pass\n");
            printf("%d\n",bar_variable);
            return;
        }
        if(a[13-R1]<0&&a[13-R2]<0&&a[13-R1-R2]<0)
        {
            printf("pass\n");
            return 0;
        }
    }
        
        
    if(bar_variable<=0)
    {
    for(i=12;i>=1;i--)
    {
        if(a[i]>0)
        {
            if(i-R1>0&&R1_moved==0)
            {
                if(a[i-R1]==-1&&R1_moved==0)
                {
                    a[i-R1]=1;
                    a[i]--;
                    c1='A';
                    d1='A';
                    R1_moved=1;
                    S1=i;
                    D1=i-R1;
                    bar_variable--;
                }
            }
            if(R1-i+1>0&&R1_moved==0)
            {   
                if(b[R1-i+1]==-1)
                {
                    b[R1-i+1]=1;
                    a[i]--;
                    c1='A';
                    d1='B';
                    R1_moved=1;
                    S1=i;
                    D1=R1-i+1;
                    bar_variable--;
                }
            }
        }
    }
    for(i=12;i>=1;i--)
    {
        if(a[i]>0)
        {
            if(i-R2>0&&R2_moved==0)
            {
                if(a[i-R2]==-1)
                {
                    a[i-R1]=1;
                    a[i]--;
                    c2='A';
                    d2='A';
                    R2_moved=1;
                    S2=i;
                    D2=i-R2;
                    bar_variable--;
                }
            }
                if(R2-i+1>0&&R2_moved==0)
                {
                    if(b[R2-i+1]==-1)
                    {
                        b[R2-i+1]=1;
                        a[i]--;
                        c2='A';
                        d2='B';
                        R2_moved=1;
                        S2=i;
                        D2=R2-i+1;
                        bar_variable--;
                    }
                }
            }

    }
        for(j=1;j<=12;j++)
        {
            if(b[j]>0)
            {
                if(j+R1<=12&&R1_moved==0)
                {
                    if(b[j+R1]==-1)
                    {
                    b[j]--;
                    b[j+R1]=1;
                    c1='B';
                    d1='B';
                    R1_moved=1;
                    S1=j;
                    D1=j+R1;
                    bar_variable=-1;
                    }
                }
            }
            if(b[j]>0)
            {
                if(j+R2<=12&&R2_moved==0)
                {
                    if(b[j+R2]==-1)
                    {
                    b[j]--;
                    b[j+R2]=1;
                    c2='B';
                    d2='B';
                    R2_moved=1;
                    S2=j;
                    D2=j+R2;
                    bar_variable=-1;
                    }
                }
            }
            
        }
        for(i=1;i<=12;i++)
        {
            if(a[i]>0)
            {
                if(R1_moved==0&&R2_moved==0)
                {
                    if(i-R1>0)
                    {
                        if(a[i-R1]>=0)
                        {
                            for(j=1;j<=12;j++)
                            {
                                if(a[j]>0)
                                {
                                    if(R1!=R2)
                                    {
                                    if((i-R1)==(j-R2))
                                    {
                                        a[i]--;
                                        a[j]--;
                                        a[i-R1]+=2;
                                        c1='A';
                                        c2='A';
                                        d1='A';
                                        d2='A';
                                        S1=i;
                                        S2=j;
                                        D1=i-R1;
                                        D2=i-R1;
                                        R1_moved=1;
                                        R2_moved=1;
                                     //   printf("Ghuusa\n");
                                    }
                                    }
                                }
                            }
                        }
                    }
                    if(R1-i+1>0)
                    {
                        if(b[R1-i+1]>=0)
                        {
                            for(j=1;j<=12;j++)
                            {
                                if(b[j]>0)
                                {
                                    if((R1-i+1)==(j+R2))
                                    {
                                        a[i]--;
                                        a[j]++;
                                        a[j+R2]+=2;
                                        c1='A';
                                        c2='B';
                                        d1='B';
                                        d2='B';
                                        S1=i;
                                        S2=j;
                                        D1=j+R2;
                                        D2=j+R2;
                                        R1_moved=1;
                                        R2_moved=1;
                                      //  printf("aayaaaa\n");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        for(i=1;i<=12;i++)
        {
            if(b[i]>0&&R1_moved==0&&R2_moved==0)
            {
                for(j=1;j<=12;j++)
                {
                    if(b[j]>0)
                    {
                    if((i+R1)==(j+R2))
                    {
                        if(b[i+R1]>=0)
                        {
                            b[i+R1]+=2;
                            b[j]--;
                            b[i]--;
                            c1='B';
                            c2='B';
                            d1='B';
                            d2='B';
                            S1=i;
                            S2=j;
                            D1=i+R1;
                            D2=i+R1;
                            R1_moved=1;
                            R2_moved=1;
                      //      printf("aaya\n");
                        }
                    }
                    }
                }
            }
        }
        for(i=1;i<=12;i++)
        {
            if(a[i]>0&&R1_moved==0)
            {
                if(i-R1>0)
                {
                    if(a[i-R1]>=0)
                    {
                        a[i]--;
                        a[i-R1]++;
                        c1='A';
                        d1='A';
                        S1=i;
                        D1=i-R1;
                        R1_moved=1;
                      //  printf("ghussa\n");
                    }
                }
                if(R1-i+1>0&&R1_moved==0)
                {
                    if(b[R1-i+1]>=0)
                    {
                        a[i]--;
                        b[R1-i+1]++;
                        c1='A';
                        d1='B';
                        S1=i;
                        D1=R1-i+1;
                        R1_moved=1;
                    }
                }
            }
            if(a[i]>0&&R2_moved==0)
            {
                if(i-R2>0)
                {
                    if(a[i-R2]>=0)
                    {
                        a[i]--;
                        a[i-R1]--;
                        c2='A';
                        d2='A';
                        S2=i;
                        D2=i-R2;
                        R2_moved=1;
                     //   printf("Ghussa\n");
                    }
                }
                if(R2-i+1>0)
                {
                    if(b[R2-i+1]>=0)
                    {
                        a[i]--;
                        b[R2-i+1]++;
                        c2='A';
                        d2='B';
                        S2=i;
                        D2=R2-i+1;
                        R2_moved=1;
                    }
                }
            }
        }
        for(i=1;i<=12;i++)
        {
            if(b[i]>0)
            {
                if(i+R1<=12&&R1_moved==0)
                {
                    if(b[i+R1]>=0)
                    {   
                        b[i]--;
                        b[i+R1]++;
                        c1='B';
                        d1='B';
                        S1=i;
                        D1=i+R1;
                        R1_moved=1;
                    }
                }
                if(i+R2<=12&&R2_moved==0)
                {
                    if(b[i+R2]>=0)
                    {
                        b[i]--;
                        b[i+R2]++;
                        c2='B';
                        d2='B';
                        S2=i;
                        D2=i+R2;
                        R2_moved=1;
                      //  printf("aaya\n");
                    }
                }
            }
        }
    }
        if(R1_moved!=0)
        {
        printf("%c%d->%c%d\n",c1,S1,d1,D1);
        }
        if(R2_moved!=0)
        {
        printf("%c%d->%c%d\n",c2,S2,d2,D2);
        }
        if(R1_moved==0&&R2_moved==0)
            printf("Pass\n");
        printf("%d\n",bar_variable);

     return 0;
}





